### PR TITLE
Remove python3.6 support

### PR DESCRIPTION
**Pull request by dvzrv**
Remove support for Python 3.6 as it is not supported by upstream anymore.

### CODE REVIEW

**Comment by dvzrv** [comment]
screenshot-2022-11-18_16-36-30

hmm :thinking:

**Comment by hartwork** [comment]
> screenshot-2022-11-18_16-36-30
> 
> hmm :thinking:

@dvzrv we can try a force push with new SHA1s (e.g. by flipping commit order in `git rebase -i HEAD~2`) or close and re-open of the PR, in hope that GitHub fixes itself about this. What do you think?

**Review by hartwork — APPROVED** [review]

**Comment by dvzrv** [comment]
> @dvzrv we can try a force push with new SHA1s (e.g. by flipping commit order in `git rebase -i HEAD~2`) or close and re-open of the PR, in hope that GitHub fixes itself about this. What do you think?

I tried with touching the commit messages, but I guess this is just some weird thing with github actions probably...

**Comment by hartwork** [comment]
> > @dvzrv we can try a force push with new SHA1s (e.g. by flipping commit order in `git rebase -i HEAD~2`) or close and re-open of the PR, in hope that GitHub fixes itself about this. What do you think?
> 
> I tried with touching the commit messages, but I guess this is just some weird thing with github actions probably...

@dvzrv Weird and buggy, yes. Would you be up to try…
```console
for i in 1 2 ; do git revert --no-edit HEAD~1 ; done
git push .......
```
with two reverting commits more to see if the CI heals and then try again with the reverts dropped. Just an idea.

**Comment by hartwork** [comment]
PS: @dvzrv the overall diff would be empty then, maybe add some bogus change on top so that GitHub won't close the PR or something. Just thinking aloud...

**Review by hartwork — CHANGES_REQUESTED** [review]
@dvzrv first half worked, nice, let's see about the second half…

**Comment by ssbarnea** [comment]
Don't worry about required, I fix that.

**Comment by hartwork** [comment]
> Don't worry about required, I fix that.

@ssbarnea how?

**Comment by ssbarnea** [comment]
But I am worried about not seeing any file updated. I was expecting metadata updated and GHA jobs removed.

**Comment by dvzrv** [comment]
Okay, but this seems to have fixed it now (I have removed the dummy commit on top).

**Review by hartwork — APPROVED** [review]
Excellent!

**Pull request merged**
