### PR TITLE
tests/test_ansi2html.py: use sys.executable instead of hardcoded python3

### LINKED ISSUE #210: Hardcoded "python3" in tests/test_ansi2html.py
`tests/test_ansi2html.py` contains a hardcoded `python3` executable name, which makes this test fail if there is no python3 available (but python3.11 or similar).

The patch is easy, I'll open a PR once Github fixes the outage that prevents forking this repository...

### PR DESCRIPTION
**Pull request by johanneskastl**
fixes #210

### CODE REVIEW

**Review by hartwork — APPROVED** [review]
While the change looks good in isolation, to get a green CI at https://github.com/pycontribs/ansi2html/actions/runs/4925721788/jobs/8800292224?pr=214#step:8:40 we probably need a dedicated pull request to appease flake8 first, and then rebase onto latest master after merge.

**Comment by johanneskastl** [comment]
> @johanneskastl with pull request #207 merged just now, there is a good chance that flake8 and the CI will be happy after a rebase onto latest `main`. Could you do that?

Sure, stay tuned...

**Comment by johanneskastl** [comment]
@hartwork  CI looks green, hooray!

**Comment by hartwork** [comment]
@johanneskastl thanks! :+1:

**Pull request merged**
