### PR TITLE
fix including of CHANGELOG.rst

### PR DESCRIPTION
**Pull request by ziegenberg**
Currently building the documentation does not include the changelog. It fails with the following error:

```
Running Sphinx v4.2.0
building [mo]: all of 0 po files
building [html]: all source files
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] api
reading sources... [ 66%] changelog
reading sources... [100%] index

/home/daniel/Development/github/ansi2html/docs/source/changelog.rst:4: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'changelog.rst'.
```

As can be seen [here](https://ansi2html.readthedocs.io/changelog.html) the changelog in the documentation is empty. The documentation built [by this CI](https://ansi2html--151.org.readthedocs.build/changelog.html) run does include the recent changelog.

### CODE REVIEW

**Comment by ziegenberg** [comment]
The `CHANGELOG.rst` is currently missing the latest 1.6.0 release. Should this be added?

**Comment by ziegenberg** [comment]
Also, I saw the [release notes 1.6.0 here on GitHub](https://github.com/pycontribs/ansi2html/releases/tag/1.6.0) contain lots of old PR like https://github.com/pycontribs/ansi2html/pull/23 and many others. Should this be fixed?

**Comment by ziegenberg** [comment]
Hi @ssbarnea!

I have a few questions:

- Should the label `docs` also be recognized as valid by the workflow? Cause I would classify this PR not as a bug but rather a doc fix
- Shouldn't `setuptools_scm` be listed as a build dependency in the `tox.ini`? Cause it's listed in `setup.cfg` as required for building the docs. If I'm wrong, I will drop my last commit.
- I added the 1.6.0 release notes as they are currently listed on GitHub to the `CHANGELOG.rst`. Should they be fixed in both places to reflect the actual state?

**Review by ssbarnea — APPROVED** [review]
You can fix release draft by updating PR titles and labels, even for merged changes. Still, if a release was already made the release notes are no longer updated and if you want to patch them, you need to manually edit the release.

It can take up to a minute for release drafter to refresh the drafter after you make a change.

And yes, feel free to remove the less interesting changes from changelog as its purpose is to inform users of the library not contributors. Contributors can always check git log. :D

**Comment by ssbarnea** [comment]
Docs label does not have any special meaning, you need to also add either `bug` or `skip-changelog` in order to decide how to be processed from the changelog point of view.

**Comment by ziegenberg** [comment]
Hi @ssbarnea!

I fixed a lot of old links (mostly 302 redirects and broken links).

Please also have a look at my proposed release 1.6.0 changelog entry. If you approve, I will edit the [1.6.0 release notes here on GitHub](https://github.com/pycontribs/ansi2html/releases/tag/1.6.0) accordingly.

For the older releases, I did not change the content, just the presentation and markup. You can find the newly rendered read the docs here: https://ansi2html--151.org.readthedocs.build/changelog.html

There is now also a sphinx linkcheck build step while building the documentation. It breaks the build if it finds broken links.

This is ready to review.

**Review by ssbarnea — APPROVED** [review]

**Comment by ziegenberg** [comment]
@ssbarnea Am I allowed to edit the Release Notes here (https://github.com/pycontribs/ansi2html/releases/tag/1.6.0) and make them the same as what is now in `CHANGELOG.rst`?

**Comment by ssbarnea** [comment]
Sure!

**Comment by ziegenberg** [comment]
Done.

**Pull request merged**
