### PR TITLE
Add API documentation generation as part of the build worflow

### PR DESCRIPTION
**Pull request by tristanlatr**
Hi,

This PR adds API documentation with `pydoctor`. 

This avoids having to skim through the code to find the right arguments to the `convert` function for instance.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
API docs should be included in normal docs and we already have a RTFD job doing that.

I do find this change useful but I do think that it should not alter CI jobs or create extra tox targets. We can squeeze the same functionality inside the standard `docs` env.

**Comment by tristanlatr** [comment]
> we already have a RTFD job doing that.

You have no links pointing to your documentation in the README!

**Comment by ssbarnea** [comment]
@tristanlatr Sorry, my mistake. I had the impression that the project already has a docs pipeline setup.

- [x] enabled RTD integration, job should run on PRs now
- [ ] include link to docs in project README and setup.cfg file, the url will be https://ansi2html.readthedocs.io - not working now as we do not have valid docs to publish yet.
- [ ] ensure there is a `tox -e docs` job that builds docs locally, for development

I am looking forward to merge your change!

**Comment by ssbarnea** [comment]
@tristanlatr Would you mind making another change that adds docs building using `tox -e docs` in such way that also RTD reports green? I think is highly desirable to first have some docs published before we add pydoctor to it. It would make the review of this feature much easier.

Probably you observed that now RTD integration is enabled, so it should not be hard to add a sphinx setup. Usually I would have done that but these days I am already at 120%.

**Comment by tristanlatr** [comment]
I’m pretty familiar with Sphinx. So im ok doing this. So I’ll configure Sphinx and get rid of my custom pydoctor script. If we are using Sphinx, I don’t think it’s really a good move to still use pydoctor, even if it proposes a nice integration with it. This project is just not big enough to really benefit from pydoctor’s level of technicality. So I think I’ll use sphinx-autoapi instead (except if you insist). That will also be nicer on the eyes. I will create a new PR for that since it’s actually a completely different thing from what I proposed I this PR.

**Comment by ssbarnea** [comment]
I agree with you on all points. In fact I never used pydoctor but i used sphinx stuff.

**Comment by tristanlatr** [comment]
See #141 instead.

**Pull request closed without merging**
