### PR TITLE
CHANGELOG.rst: Fix misleading 1.6.0 entry and missing 1.7.0 entries

### PR DESCRIPTION
**Pull request by hartwork**
@ssbarnea good to merge?

### CODE REVIEW

**Comment by hartwork** [comment]
PS: @ssbarnea I lack permissions to set labels as requested by CI https://github.com/pycontribs/ansi2html/runs/5015881284?check_suite_focus=true#step:4:13 it seems. Can you help?

**Comment by ssbarnea** [comment]
In fact last two releases were not included in CHANGELOG.md file. I fixed the python version on https://github.com/pycontribs/ansi2html/releases already but it would be useful if you could just mention that changelog is now available at https://github.com/pycontribs/ansi2html/releases

**Comment by ssbarnea** [comment]
If you still think that the file is very useful, just add the last two missing releases from the releases page (body is already markdown) and them here. It is up to you.

I am inclined to minimize the churn on new releases, and because the github releases are automatically generated on each merge, i prefer to avoid having to remember to update one extra document. Still, I am also aware that some people consider these files essential.

**Comment by hartwork** [comment]
@ssbarnea I understand that having GitHub generate them is convenient. Right now my vote would be to copy from the into the file, and to keep the file around.

**Comment by ssbarnea** [comment]
> @ssbarnea I understand that having GitHub generate them is convenient. Right now my vote would be to copy from the into the file, and to keep the file around.

Just do it. Use edit to get markdown source for the two missing releases and repurpose this PR.

**Comment by hartwork** [comment]
@ssbarnea I had look at the change log generator now. It seems it produces markdown (while we have .rst) and there is no classification into buckets like "bugfixes" and "minor changes". So to me it looks like the auto generator is helpful but maybe best serves to feed a human post-processor rather than the eventual reading user.

**Comment by ssbarnea** [comment]
Ahh, in that case it would be easier to convert rst to markdown, or just do the conversion manually for now. During the last year I slowly started to migrate projects to markdown as it become ubiquitous and it makes much easier for others to contribute. Also Sphinx got good  support for it too.

**Comment by hartwork** [comment]
@ssbarnea I have added the 1.7.0 entries now for review.
Regarding markdown, RST has some nasty properties e.g. with regarding to some things not nesting, so I'm not against migration to markdown, as long as it's after this pull request :smile: Pandoc can likely do most of the conversion work.

**Pull request merged**
