### PR TITLE
Add test coverage

### PR DESCRIPTION
**Pull request by ziegenberg**
Adds test coverage data

### CODE REVIEW

**Comment by ziegenberg** [comment]
This is ready for review.

**Comment by ssbarnea** [comment]
If you want to complete the coverage enablement, try to also upload the data to codecov.io -- You can inspire from https://github.com/ansible-community/ansible-compat/blob/main/.github/workflows/tox.yml#L217-L222 -- it is a little bit dated but still works.

I will enable codecov integration and we will see jobs reporting when coverage goes down.

**Comment by ziegenberg** [comment]
I will try to add the according workflow steps.

**Comment by ziegenberg** [comment]
I will look into this a bit later this week.

**Comment by ssbarnea** [comment]
> I will look into this a bit later this week.

No hurry, fixing stuff in small steps is the best approach as we never know how much time we have available. I mentioned that only for follow-ups, it was not a required for enablement.

Still, this needs to report green to merge it.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Cannot really review if CI is reporting red.

**Comment by ziegenberg** [comment]
I'll revert 9387334b3ed621bcfbfbe9fd0f035d3143294311 for now and will add this via it's own PR later on.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
