### PR TITLE
Fixes to respect bright colors in palette

### LINKED ISSUE #133: Bright color generation is buggy
Copying this from PR #126 

> It seems there are two errors in the existing logic in style.py:
> 
> * When a palette defines the upper 8 colors (the "bright" colors), the existing code overwrites them anyway using the results of intensify.
>  * When a palette does not define the upper 8 colors, the existing code does not define replacements for them in the 256-color palette rule families.
> 
> In other words, the code was overwriting some of the explicitly defined colors, but also failing to provide automatically brightened colors when it could have :-)

### PR DESCRIPTION
**Pull request by echuber2**
Fixes #133 

It seems there are two errors in the existing logic in style.py:

1. When a palette defines the upper 8 colors (the "bright" colors), the existing code overwrites them anyway using the results of `intensify`.
2. When a palette does not define the upper 8 colors, the existing code does not define replacements for them in the 256-color palette rule families.

In other words, the code was overwriting some of the explicitly defined colors, but also failing to provide automatically brightened colors when it could have :-)

Note that with this fix in place, the existing test suite doesn't "pass" because the output colors will be different. For some users, this may be an unexpected change in behavior. In that case, maybe the old behavior should be preserved as a default while the new behavior is toggled optionally.

The code could be optimized to not make so many redundant calls to `intensify`, but I haven't bothered to make that change here.

### CODE REVIEW

**Comment by echuber2** [comment]
Now that the code respects the explicit definitions of the upper 8 colors, it was necessary to remove the "`*2`" on the `osx` 8-color palette so that its bright set will still be generated.

**Comment by echuber2** [comment]
@ssbarnea Can you run the CI checks on this? It failed linting before but I didn't check the log before the log expired, so I'm not sure what's wrong.

**Comment by ssbarnea** [comment]
Sure, just ping me when needed.

**Comment by ssbarnea** [comment]
@echuber2 I send you an invite so you do not need approval to run CI. I hope you can at least partially help with #135

**Comment by echuber2** [comment]
@ssbarnea Hi, so, it appears that because this PR effectively changes the color palette that is generated, the unit tests are going to fail unless they are also changed accordingly. Would you or someone else like to proofread what I've done here before I try to change the tests themselves? Thanks.

**Comment by ssbarnea** [comment]
I am going to close this because I did not find any attempts to bring it to ready for review state. If things change I am more than happy to reopen it.  Others are also welcomed to attempt to get the incomplete code and fix it.

**Comment by echuber2** [comment]
The code isn't incomplete. It's the old unit tests that need fixing as they are based on the old (broken) code. I don't have time to manually create the fixed tests right now but I am hoping that with the branch closed, it will not be overlooked or deleted in the future before someone finishes merging it.

**Comment by ssbarnea** [comment]
Is failing most CI jobs, which counts as... not complete. You want to create a feature branch directly inside the project?

I will reopen it, hoping someone takes over and fixes the tests for it.

**Comment by echuber2** [comment]
What needs editing is `produce_headers.txt`. To make sure this is correct, rather than just editing it in place to pass the tests, I think I need to produce a mockup visually demonstrating the generated palettes before and after the proposed change. This should also illustrate the original flaw.

**Comment by hartwork** [comment]
ansi2html_styles_main
[`render_scheme_as_html.py`](https://github.com/pycontribs/ansi2html/files/7975179/render_scheme_as_html.py.txt)

**Comment by echuber2** [comment]
Thanks, that's a good place to start. However this is rendering the hard-coded scheme colors directly, which leaves out the logic that this would fill in on-demand. I think what we need to do is generate the styles for real (e.g. `get_styles`) and compare the results. I thought we could set up an ANSI-coded test string using all the colors, process it in the usual way, and look at that result.

**Comment by hartwork** [comment]
@echuber2 yes, I'm at `get_styles`, stay tuned :smile:

**Comment by echuber2** [comment]
I see, thanks for helping. There's no hurry -- I thought I'd leave a note to myself until I can take a look at it again. If this works well, maybe the palette preview could just be part of CI in the future too.

**Comment by hartwork** [comment]
This is what `get_styles` does to the palettes:
ansi2html_get_styles
[`render_scheme_get_styles.py`](https://github.com/pycontribs/ansi2html/files/7975583/render_scheme_get_styles.py.txt)

**Comment by hartwork** [comment]
So the behavior is:
- For 4-bit mode the upper half of the palette is ignored and classes `.(ansi|inv){90..97,100..107}` are generated from the lower half of the palette. That seems unfortunate indeed.
- For 8-bit mode, the full palette is respected.

**Comment by echuber2** [comment]
@hartwork Great, thanks. Looks like that's the output for the "before" case. I ran it too, with the "before" (main branch) and "after" (this branch):

Before:
get_styles_before_PR
After:
get_style_after_PR

I'm not sure if I'm handling the "dark background" case properly here.

**Comment by hartwork** [comment]
@echuber2 at least for some palettes the situation arguably got worse, e.g. palette "ansi2html" lost it's effective brightening/darkening feature. Let's think more about our options. I think the implementation will be easy once we know where to go from a user/requirements perspective.

**Comment by echuber2** [comment]
If people specify 16 colors, I thought it implies they want those exact 16 colors. If they want the latter 8 colors to be auto-generated, they need only specify an 8-color palette. The OSX palette demonstrates what it actually does in that case.

Would it make sense to make the "old" mode the default for the time being, with an argument to opt-in to the "new" mode?

**Comment by hartwork** [comment]
Hi @echuber2,

I experimented a bit more, with Python >=3.6 code, Yakuake, Terminator, on GNU/Linux.  I found that:
- In both Terminator and Yakuake all palettes have 16 colors.
- Most themes have the second half be brighter versions of the first half. Common exception is theme "Solarized".
- (Both Yakuake and Terminator agree on the first 16 color values across 3-bit, 4-bit and 8-bit ANSI codes (see screenshot for Terminator)  Exception in Terminator: when checkbox "Show bold text in bright colors" is off then 3-bit bright colors will use the regular colors from the first half of the palette.)
- That means that the auto-brigthening code in ansi2html does a disservice to (above all) the solarized scheme.

I think the key questions left to answer are:
- With _light_ backgrounds, terminals don't flip brightened colors in the palette to darkened ones: They use them as-is.  If the terminal doesn't do that, should ansi2html? Not at all or not by default?
- Does macOS default terminal(?) really have the brightened colors identical or do we need to fix palette "osx" in ansi2html?

If someone wants to play with color display on their terminal (e.g. on macOS), here's a Gist and example output:

[GitHub Gist `demo_ansi_colors.py`](https://gist.github.com/hartwork/a2a1c1a1b81a35afddbbe96551c6e9f7).

For Terminator on Linux with Palette "Ambience" over "Gray on black":
ansi_terminator_ambience

Best, Sebastian

**Comment by hartwork** [comment]
Based on https://i.stack.imgur.com/uMHPG.jpg I'm currently expecting that the default ANSI color palette on macOS does not have bright colors equivalent to non-bright (but 16 distinct colors) but we'll need someone with macOS and default colors to verify.

Once the "osx" scheme is fixed, we should maybe just drop the auto-intensification code and fully respect the upper half of the color scheme because (1) it's what terminals do even with light backgrounds, (2) ansi2html output can probably be expected to look like terminals, (3) it unbreaks scheme "solarized", (4) it's consistent with 8-bit ANSI color mode, and (5) if anyone turns out needing darker or different colors, adding a scheme with those precise colors seems to cover all we could need. What do you think?

**Comment by jeffgerickson** [comment]
FYI: The Terminal app built into Mac OS 11.6.1 comes with several profiles, with varying ANSI color palettes.  Here is the palette for the "Basic" profile, which appears to be the default:
image

Here's the "Solid Colors" palette:
image

Here's the "Silver Aerogel" palette:
image

The other seven built-in profiles all use the same palette:
image

iTerm2 (the official successor to iTerm) uses a different default color palette:
image

**Comment by hartwork** [comment]
@jeffgerickson sweet, thank you! :+1: :+1: 

@echuber2 my plan now would be to…
- extract RGB hex cods from @jeffgerickson "Basic" theme screenshot using a color picker
- put those into scheme "osx" in ansi2html, then 
- make the code for `.ansi{90..97,100..107}` and `.inv…` use the upper half of the palette verbatim
- (while keeping function `intensify` around for API compatibility).

Does that sound like a plan? Would you want to do that in this very pull request or should take over and make a new one? I'm good either way.

**Comment by echuber2** [comment]
Thanks to Jeff for the palettes. @hartwork I'm fine with updating the osx palette, but the bright color generation seems to have a legitimate use, to avoid missing styles or crashing bugs in the get_styles call, when users only specify the first 8 colors of a 16-color palette (note it also does this in 256-color mode). If users specify all 16 colors, it does use those without alteration, as the calls to `intensify` are skipped. If nothing else, if fewer than 16 colors are specified, I think the first 8 colors should be replicated as the second set of 8 colors.

**Comment by echuber2** [comment]
As you mentioned the damage done to Solarized with the old version, I thought I should reiterate that my PR branch doesn't edit the colors if they're already in the palette. Here's the part where the intensify calls are skipped in that case (`else` branch):

https://github.com/echuber2/ansi2html/blob/aa7c241637602282f706d34243ed1308340b3efc/ansi2html/style.py#L216-L239

I notice that the only way for users to customize the schemes currently is to edit the library source, so I wonder how many have actually done so. If anyone did have previous palettes defined with only 8 colors, I wouldn't want them to suddenly get an exception thrown after merging the library update with their copy, so I think duplicating the initial 8 colors is better than not generating the "bright" set at all. If we don't want to generate anything, then we should explicitly check that 16 colors were defined and display a clear error message about that.

**Comment by hartwork** [comment]
Hi @echuber2,

let me try get a few things out of the way, first:

> I notice that the only way for users to customize the schemes currently is to edit the library source

I don't think that's true unfortunately. Let me prove it you:
```python
from ansi2html.style import SCHEME, get_styles

SCHEME['night'] = ['#000000' for _ in range(16)]

get_styles(scheme='night')
```
It can be argued whether that's official API but it does work without editing sources.

Since commit 5e55018eb331e2d934215821e874e30eab20e6ef of ansi2html 1.0.8 all schemes have specific 16 color slots and the current implementation of `get_styles` would crash with fewer, so we can safely assume, that whoever passed a custom palette had to put >=16 values into it.

> If anyone did have previous palettes defined with only 8 colors, I wouldn't want them to suddenly get an exception thrown after merging the library update with their copy, so I think duplicating the initial 8 colors is better than not generating the "bright" set at all. If we don't want to generate anything, then we should explicitly check that 16 colors were defined and display a clear error message about that.

People with modified forks are on their own, that's not our job, honestly. What we can do is do more input validation, including a raising an exception if we find the passed color scheme does not exist or is not an "indexable vector" with 12 elements.

> [..] the bright color generation seems to have a legitimate use, to avoid missing styles or crashing bugs in the get_styles call, when users only specify the first 8 colors of a 16-color palette (note it also does this in 256-color mode). If users specify all 16 colors, the updated code does use those without alteration, as the calls to `intensify` are skipped. If nothing else, if fewer than 16 colors are specified, I think the first 8 colors should be replicated as the second set of 8 colors. (However, I'm not sure what users _expect_ to happen in that case. In the previous behavior, some "bright" colors were indeed written out although they weren't the right ones.)

I don't see why we'd want to start supporting less than 16 colors now. The only thing I see potential value in is the "darkening mode" with `dark_bg=False` where the upper half of the palette is replace by darker (rather than brighter colors). If that's something we want to rescue (despite termninals not doing that) we would need a new keyword flag a la `auto_darken=False` and make the code respect it. The best way I see to do that would be:
```python
from ansi2html.style import SCHEME, intensify
...
pal = SCHEME['dracula']  # arbitrary choice, as used in get_styles
auto_darken = True       # new flag
...
if auto_darken:
    pal = tuple(pal[:8]) + tuple(intensify(color, dark_bg=False) for color in pal[8:])
...
```
Then all code coming after would use values from pal, consistently.

> As you mentioned the damage done to Solarized with the old version, I thought I should reiterate that my PR branch doesn't edit the colors if they're already in the palette. Here's the part where the intensify calls are skipped in that case (`else` branch):
> 
> https://github.com/echuber2/ansi2html/blob/aa7c241637602282f706d34243ed1308340b3efc/ansi2html/style.py#L216-L239

Regarding damage to solarized, I was referring to the unpatched code in branch `main`.

Thanks for the invitation to collaborate right in https://github.com/echuber2/ansi2html. I have created a backup branch `get-styles-fixes-BACKUP-2022-02-06` with the original current and replaced the content with what I think we should do for a continued discussion. I have put in a version with a new flag `auto_darken`, but we can drop it if you consider it unnecessary. There is no command line argument for it yet, and the osx palette is also unfixed. I hope this is a good first step, let me know what you think.

**Comment by echuber2** [comment]
Hm, you are right about the previous behavior crashing and the possibility of mutating `SCHEME`, so perhaps there's no need for the auto-generation. I'd already forgotten the circumstances when I initiated this PR. We wanted the verbatim 16 colors to be respected first and foremost, but the (non-working) auto-generation code was already there, so I tried to work it into my original PR.

I am a little bothered that you force-pushed to the branch (I was not expecting that). Perhaps I'm being petty, but the commit history now shows that you discovered the bug yourself. At any rate, I think your plan is fine, but perhaps there should be an `auto_brighten` option as long as there is an `auto_darken` one too (or that could be a separate PR as it adds a feature, beyond fixing the bug). I can work on transcribing the osx palette and fixing the tests but it will probably have to wait until tomorrow.

**Comment by hartwork** [comment]
> Hm, you are right about the previous behavior crashing and the possibility of mutating `SCHEME`, so perhaps there's no need for the auto-generation.

If no one really needs it, we could also go for dropping it complete. No need for a zombie, if no one asks for it.

> I am a little bothered that you force-pushed to the branch (I was not expecting that). Perhaps I'm being petty, but the commit history now shows that you discovered the bug yourself.

@echuber2 thanks for speaking up and sorry for stepping on your toes, that was not my intention, it was a misunderstanding. Only replacing the past history made sense to me with the given history and the invitation to use your repository (because only access to that branches is what I gain from that repo over my own fork), but this is proof I misunderstood, and **I have restored the original state** based on the backup branch I created. It's the very same SHA1 now. The two git-am patches I put in were these (for reference or re-use under CC-0 "public domain"):
- [`0001-style.py-Make-get_styles-respect-the-upper-half-of-t.patch.txt`](https://github.com/pycontribs/ansi2html/files/8011452/0001-style.py-Make-get_styles-respect-the-upper-half-of-t.patch.txt)
- [`0002-style.py-Handle-unsupported-color-schemes.patch.txt`](https://github.com/pycontribs/ansi2html/files/8011453/0002-style.py-Handle-unsupported-color-schemes.patch.txt)

I would suggest then that in your PR I do review and you do the coding. If you want it the other way around, let me create a new PR where I do the code and you do the review. I'm good either way.

> At any rate, I think your plan is fine, but perhaps there should be an `auto_brighten` option as long as there is an `auto_darken` one too (or that could be a separate PR as it adds a feature, beyond fixing the bug).

I didn't add one because I didn't see need for it. After all, the palette already has the bright version and if those values are not good then let's fix them or create modified copies of that palette. I just don't see the need. Do you?

> I can work on transcribing the osx palette and fixing the tests but it will probably have to wait until tomorrow.

Alright :+1:

**Review by hartwork — CHANGES_REQUESTED** [review]
@ssbarnea since you requested my review: Status quo is that I am waiting for hearing back from @echuber2 at the moment. There was a misunderstanding, I apologized, I hope @echuber2 and I are still good, now we need to channelize research results into this pull request or a new one some way now, the hard part is already done.

**Comment by echuber2** [comment]
Thanks for putting the branch back. I spliced in your suggestions and made the requirement for 16 defined colors explicit. It may be there is no need for auto _bright_ color generation, but it seems like it would be a convenience if someone only had specific colors in mind for the first 8 but still wanted the bright ones added. When I first looked at the repo, there was a `*2` on the osx palette where the previous contributor had not bothered specifying the latter half; perhaps they realized the latter half was being overwritten no matter what at that point. I don't want to insist on adding auto brightening for this PR but I might rename the PR now that the focus has been clarified.

I will still have to do the chores of fixing the osx palette and the unit tests. I will try to do that today.

**Comment by hartwork** [comment]
@echuber2 thanks for the updates! It is technically not too late to drop the auto-darken code again. It would make things simpler, resolve the question about darkening/brightening asymmetries, the lack of a CLI option, all that. Do we even need it?

I will go extract color codes from the screenshot myself as well now, so that I have values to compare against when doing review.

**Comment by echuber2** [comment]
We can just remove the auto_darken option for now. It could be a separate PR if needed later. However I'm not sure if this will alarm some users since the existing (buggy) behavior had been generating dark colors when `dark_bg=False`. At any rate, this PR will slightly change the bright colors being output compared to before, so it may disrupt some user's CI no matter what. If more work is needed to make appropriate CLI options then I do think it would make sense to add in a separate PR.

**Comment by hartwork** [comment]
@echuber2 okay nice, let's drop it then and bring it back in an explicit saner version when (and if) we get bug reports about people missing the weird current behavior after the next release.

**Comment by hartwork** [comment]
> FYI: The Terminal app built into Mac OS 11.6.1 comes with several profiles, with varying ANSI color palettes. Here is the palette for the "Basic" profile, which appears to be the default: image

@echuber2 I extracted "Basic" from that^^ screenshot to be:

```python
{
    "osx" (  # macOS theme "Basic"
        '#000000',
        '#800000',
        '#008000',
        '#808000',
        '#000080',
        '#800080',
        '#008080',
        '#808080',
        '#666666',
        '#e60000',
        '#00d900',
        '#e6e600',
        '#0000ff',
        '#e600e6',
        '#00e6e6',
        '#e6e6e6',
    )
}
```

Interestingly, our code on `master` has `#c23621` as the second color, which I cannot find in *any* of the screenshots. To me that means, that commit 2176bc4d050f52b69dd9227e29508a9dfd2e1b0a adding color theme "osx" had a different source of "os X terminal" or the scheme has change since 2013 on macOS side. @schettino72 could you help us on the origin on the colors for scheme "osx"? Can you confirm that default colors have changed since then?

@echuber2 I am currently considering to keep the spirit of the current osx palette unchanged but to put the previous effective light values in like this:
```
In [6]: from ansi2html.style import intensify, SCHEME

In [7]: new_osx = SCHEME["osx"][0:8] + tuple(
   ...:     intensify(color, dark_bg=True) for color in SCHEME["osx"][0:8]
   ...: )
   ...: new_osx
Out[7]: 
('#000000',
 '#c23621',
 '#25bc24',
 '#adad27',
 '#492ee1',
 '#d338d3',
 '#33bbc8',
 '#cbcccd',
 '#404040',
 '#ff7661',
 '#65fc64',
 '#eded67',
 '#896eff',
 '#ff78ff',
 '#73fbff',
 '#ffffff')
```
What do you think?

**Comment by hartwork** [comment]
> Perhaps your `new_osx` should be put in under the name `osx`, and we can also have `osx-basic` and `osx-brighter` (or `osx-solid-colors`).

@echuber2 that sounds great, and `osx`, `osx-basic` and `osx-solid-colors` would be great naming (because of 1:1 mapping) and consistent with the existing dash in `mint-terminal` :+1:

**Comment by echuber2** [comment]
Here's the updated preview. The three lines for each palette appear the same now, but the preview does not show the terminal background, etc. which still do change based on `dark_bg`.

revised-osx-palettes

**Comment by echuber2** [comment]
I think it's okay now but I'm not sure if something needs to be done about the codecov.

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
> I think it's okay now but I'm not sure if something needs to be done about the codecov.

Coverage looks ok to me. Sometimes we need to use common-sense and disregard what it reports.

**Comment by ssbarnea** [comment]
> Hi @echuber2 .
> 
> I reviewed all but `osx-solid-colors` color values now. In general, I think the PR is in a great state now, very well done, thank you! 👍
> 
> My potentially final question here on details would be:
> 
> * Do you want me to double-check `osx-solid-colors`?
> * Do we want to add function `darken_bright_colors` despite no tests and no users?  I don't think it's a big problem, but I also find that the code is easy enough to re-do in 1 minute later if needed, and maybe just not adding that function is "even better"?
> * There are "26 commits" in here according to GitHub. I would strongly advise against rebase-merging due to that. If everyone is expecting this to be squash-merged, then it's a non-issue.  (Personally and elsewhere I would always ask to get PRs clean of merge commits and to rebase against latest `master`.)
> 
> Thanks for your work on this matter! 👍

If that is ok remove your requested changes status so I can squash-merge it without using admin rights. Or you can to the squash merge yourself.

In general I do only squash merged but sometimes I make mistakes (same reasons as you).

**Comment by hartwork** [comment]
@echuber2 thank you! :pray:

**Pull request merged**
