### PR TITLE
Add truecolor support

### PR DESCRIPTION
**Pull request by miltolstoy**
Resolves https://github.com/pycontribs/ansi2html/issues/101

### CODE REVIEW

**Review by ssbarnea — COMMENTED** [review]
In general it looks ok but ping me back once you pass the linters.

**Comment by miltolstoy** [comment]
> In general it looks ok but ping me back once you pass the linters.

Of course, just didn't have time for it yet.

**Comment by ssbarnea** [comment]
Any change to add some tests to cover for the reducing of code coverage? Click on the codecov report to see what you added but without test coverage.

Sorry for nagging you about that but reducing coverage is a recipe for future regressions.

**Comment by miltolstoy** [comment]
> Any change to add some tests to cover for the reducing of code coverage? Click on the codecov report to see what you added but without test coverage.

No problem, I'll add more negative tests.

**Comment by miltolstoy** [comment]
codecov/project — 94.16% (+1.31%) compared to da3a275

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
I made a pre-release https://github.com/pycontribs/ansi2html/releases/tag/1.7.0a0 -- feel free to make use of it and ping me back in one week if it proves to work, so I can make it a full release.

**Comment by miltolstoy** [comment]
> I made a pre-release https://github.com/pycontribs/ansi2html/releases/tag/1.7.0a0 -- feel free to make use of it and ping me back in one week if it proves to work, so I can make it a full release.

@ssbarnea 
Works fine for my case. You can make a full release.
Thank you.

**Pull request merged**
