### PR TITLE
Strip out ANSI codes ansi2html can't process

### PR DESCRIPTION
**Pull request by Xyene**
This prevents issues with converting outputs (e.g. from compilers) that contain codes like `\33[?1h`, `\33=`, etc. that `ansi2html` can't currently process.

### CODE REVIEW

**Comment by Xyene** [comment]
Hi @ssbarnea, thanks for taking up ownership of this project!

We've been running this patch in prod since 2019, where it processes thousands of compiler logs daily.

Unfortunately, a lot of time has passed since opening this PR, and nowadays I no longer have the spare cycles available to address the requested changes. Feel free to close this PR, adapt it, or whatever else you wish.

I do believe this PR fixes #102 and #105, so I think some variant of this logic would be good to have as part of `ansi2html`.

**Comment by ssbarnea** [comment]
@Xyene Please fix the conflicts so I can merge it. Otherwise I will have to close it.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
This change does not add any new tests and based on what it does I feel that at least one test including a to be stripped sequence needs to be included. The danger of messing
the processing too big not to do it.

**Comment by ssbarnea** [comment]
@tristanlatr Any chance you could takeover this patch? While I find it useful, I do not dare to merge it without some tests.

**Comment by ssbarnea** [comment]
Closing as this also went against develop branch, which we no longer use.

**Pull request closed without merging**
