### PR TITLE
fix special character escaping for latex

### PR DESCRIPTION
**Pull request by ususdei**
The characters '\\' , '{' , '}' were not properly escaped before.

### CODE REVIEW

**Comment by ralphbean** [comment]
Looks like this only works on python3.  Can you adjust this to also support python2?

**Comment by ususdei** [comment]
This turned out to become even uglier than I expected.
Translating single characters to replacement strings of arbitrary length in python 2 isn't trivial at all.
I tested this now for python 2.7.12 and python 3.5.2. It certainly does not work for python 3.0.

**Comment by ralphbean** [comment]
The py2 tests still fail here.

I just added a `tox` configuration on the develop branch if you'd like to rebase against develop and use that for testing.

**Comment by normanr** [comment]
instead of maketrans/translate (and the weird hacks for python2), why not just do:
`re.sub('[%s]' % ''.join(escape_map.keys()), lambda m: escape_map[m.group(0)], s)`

**Comment by ssbarnea** [comment]
Closing as @ususdei seems not active anymore but I am more than happy to revive it if needed.

**Pull request closed without merging**
