### PR TITLE
fix solarized scheme

### PR DESCRIPTION
**Pull request by kaspar030**
The solarized scheme from 1.5.2 doesn't look at all like https://ethanschoonover.com/solarized/ would make me think.

IMO, the color values are off.
Also, dark and light mode choose slightly different colors, and don't just invert.

This PR refactors the scheme to use a map of the "official" color names (from above's link).
It allows schemes to override foreground and background color, depending on dark_bg.

Find some converted `ls --color=always` output from master and this PR attached.

[testfiles.zip](https://github.com/ralphbean/ansi2html/files/5096070/testfiles.zip)

### CODE REVIEW

**Comment by kaspar030** [comment]
- fixed reversed fg/bg colors in non-solarized case
- fixed bold #AAAAAA -> #FFFFFF

**Review by ssbarnea — CHANGES_REQUESTED** [review]
This change seems to be intrusive and not following the other existing themes, making harder to maintain them.

I think we should keep the same formatting and maybe even implement these changes in smaller chunks?

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I do not think we should change the format used to store the scheme for SOL alone or during the same change.

Those two changes are unrelated, both good but not at the same time. If we are to change the format we need to do it for all themes at once.

**Comment by kaspar030** [comment]
> I do not think we should change the format used to store the scheme for SOL alone or during the same change.

Ok, I'll rework the PR!

**Comment by ssbarnea** [comment]
@kaspar030 If is easier for you you can make another one.

**Comment by ssbarnea** [comment]
Closing due to lack of updates. Feel free to reopen if you do have time to rebase it.

**Pull request closed without merging**
