### PR TITLE
style.py: Drop unused CSS class .bold

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Comment by hartwork** [comment]
@ssbarnea do you have a minute for review?

**Review by ssbarnea — APPROVED** [review]
I have some mixed feelings about that as I know that many terminals still support bold instead of bright.

Wait for extra reviews on this change.

**Comment by hartwork** [comment]
> I have some mixed feelings about that as I know that many terminals still support bold instead of bright.
> 
> Wait for extra reviews on this change.

The class is unused altogether. No? There is no semantic effect expected.

**Comment by hartwork** [comment]
> @hartwork Can you please rebase?

@ssbarnea done

**Pull request merged**
